const STANDARD_CHAT_EMOJI_CODES = new Set([
  ':all-in:',
  ':angry:',
  ':beer:',
  ':cash:',
  ':champagne:',
  ':clover:',
  ':club:',
  ':coffee:',
  ':cocktail:',
  ':cool:',
  ':crown:',
  ':cry:',
  ':devil:',
  ':diamond:',
  ':diamond-suit:',
  ':fire:',
  ':flush:',
  ':heart:',
  ':heart-suit:',
  ':juice:',
  ':joker:',
  ':laugh:',
  ':lmao1:',
  ':lmao2:',
  ':lol:',
  ':mocktail:',
  ':no:',
  ':pair:',
  ':party:',
  ':rofl:',
  ':rolling:',
  ':rolling2:',
  ':shit:',
  ':smile:',
  ':spade:',
  ':wheelchair:',
  ':wine:',
])

const VIP_CHAT_EMOJI_CODES = new Set([
  ':1v1:',
  ':vip-all-in:',
  ':vip-angry:',
  ':vip-applause:',
  ':vip-big-pot:',
  ':vip-blackjack-21:',
  ':vip-bluff:',
  ':vip-bust:',
  ':vip-cheers:',
  ':vip-crying:',
  ':vip-double-down:',
  ':vip-facepalm:',
  ':vip-fold:',
  ':vip-good-game:',
  ':vip-hit-me:',
  ':vip-hot-streak:',
  ':vip-join-me:',
  ':vip-laughing:',
  ':vip-love-it:',
  ':vip-lucky-ace:',
  ':vip-raise:',
  ':vip-respect:',
  ':vip-rolling:',
  ':vip-royal-flush:',
  ':vip-shocked:',
  ':vip-stand:',
  ':champagne:',
  ':choco-milkl:',
  ':cocktail:',
  ':fuck-you:',
  ':gg:',
  ':good-luck:',
  ':mid-fingers:',
  ':milk:',
  ':mojito:',
  ':noob:',
  ':op:',
  ':poison:',
  ':rofl2:',
  ':rolling3:',
  ':rolling4:',
  ':sake:',
  ':shit:',
  ':whisky:',
  ':wine:',
])

export function sanitizeChatText(rawText: string, hasVipAccess: boolean) {
  return rawText
    .replace(/:([a-z0-9-]+):/g, (match) => {
      if (STANDARD_CHAT_EMOJI_CODES.has(match)) return match
      if (VIP_CHAT_EMOJI_CODES.has(match)) {
        return hasVipAccess ? match : ''
      }
      return match
    })
    .replace(/[ \t]{2,}/g, ' ')
    .trim()
}
